apiVersion: apps/v1
kind: Deployment
metadata:
  name: pavan-go-movies
spec:
  selector:
    matchLabels:
      app: go-movies
  template:
    metadata:
      labels:
        app: go-movies
        author: pavan
    spec:
      containers:
      - name: go-movies 
        image: edge31acr.azurecr.io/pavangomovies:41
        resources:
          limits:
            memory: "20Mi"
            cpu: "100m"
        ports:
        - containerPort: 8000
      imagePullSecrets:
        - name: edge31acr
